Update 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,25 +1,24 @@
-#!/usr/bin/env bash
-# Check if all the required parameters are passed
-if [ $# -lt 4 ]; then
-  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-  exit 1
+#!/bin/bash
+
+# Check if the number of parameters is less than 4
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
 fi
 
 # Assign parameters to variables
-file_path=$1
-server_ip=$2
-username=$3
-ssh_key=$4
-
-# Disable strict host key checking
-export SSH_OPTIONS="-o StrictHostKeyChecking=no"
+FILE_PATH="$1"
+SERVER_IP="$2"
+USERNAME="$3"
+SSH_KEY_PATH="$4"
 
 # Transfer the file using scp
-scp -i "$ssh_key" $file_path $username@$server_ip:~
+scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
 
-# Check the exit status of the scp command
+# Check if scp was successful
 if [ $? -eq 0 ]; then
-  echo "File transferred successfully!"
+    echo "File transfer successful."
 else
-  echo "Failed to transfer the file."
+    echo "File transfer failed."
+    exit 1
 fi
